# Generated by Django 4.2 on 2023-05-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.IntegerField(blank=True, db_column='itemID', null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.IntegerField(blank=True, db_column='itemID', null=True)),
                ('release', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Release',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taggins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Taggins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('itemid', models.AutoField(db_column='itemID', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('hash', models.TextField(blank=True, null=True)),
                ('thumbnail', models.TextField(blank=True, null=True)),
                ('found', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Items',
                'managed': True,
            },
        ),
    ]
