# Generated by Django 4.2 on 2023-05-12 21:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('STLViewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
